# Generated by Django 6.1.1 on 2026-09-05 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0002_initial'),
        ('aledb_sample', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreseqRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample_name', models.CharField(max_length=200)),
                ('arguments', models.TextField(blank=True)),
                ('read_files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('imported', 'Imported'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('report_stored', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breseq_runs', to='aledb_experiment.experiment')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breseq_runs', to='aledb_sample.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
