# Generated by Django 6.1.1 on 2026-09-06 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `__first__` rather than a migration name: this plugin is a separate repository, and
    # mutint-core is free to renumber, squash or collapse its own history without knowing
    # this file exists. The models named below are created in their app's *first* migration,
    # which is all a foreign key to them needs -- mutint_experiment's later migrations only
    # add fields and constraints to core's own tables.
    #
    # `makemigrations` emits concrete names and will never emit this; regenerating this file
    # reverts the sentinel silently. Re-apply it when you do.
    dependencies = [
        ('mutint_experiment', '__first__'),
        ('mutint_sample', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreseqRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample_name', models.CharField(max_length=200)),
                ('arguments', models.TextField(blank=True)),
                ('trim_reads', models.BooleanField(default=True)),
                ('read_files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('imported', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breseq_runs', to='mutint_experiment.experiment')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breseq_runs', to='mutint_sample.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
