# Generated by Django 6.1.1 on 2026-09-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_breseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breseqrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('imported', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
