# Generated by Django 6.1.1 on 2026-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_breseq', '0002_alter_breseqrun_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breseqrun',
            name='report_stored',
        ),
    ]
